### ISSUE TITLE
What is the effect of using mean speaker embedding in Naive model training?

### ISSUE THREAD

**Issue by MuruganR96** [CNChTu/Diffusion-SVC#48]
Thank you for this wonderful project sharing as open source.

I couldn't see **args.model.use_speaker_encoder** in any of the config files in the configs folder. but an option is there in preprocess.py

I have a couple of questions.
1. What is the effect of using mean speaker embedding in Naive model training / Shallow diffusion? Will it increase the speaker similarity along with quality?
2. Why computed mean embedding instead of utterance level speaker embedding?
3. Any naive models released which is enabled as args.model.use_speaker_encoder true?

Thanks. I am looking forward to seeing your commands :)

**Comment by CNChTu** [comment]
Of course:

0. Thank you for getting interested in this project!
1. For the first question, I'm unaware since these codes have never truly functioned and are just a remnant from past projects.
2. Same as the first question, since the codes have never properly functioned, so there‘s no worry about its effect.
3. So, we don’t actually have any model that has configuration of enabling args.model.use_speaker_encoder to be true. Due to these codes are considered as historical remnants, they will be removed in the future.

Thanks again for bringing up these questions!hope you enjoy this project, Feel free to ask furthermore questions if you have any.
